# Generated by Django 3.1.2 on 2020-11-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('place', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=9)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('allergies', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
