# Generated by Django 3.1.2 on 2020-11-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('phone_number', models.CharField(max_length=9)),
                ('age', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], max_length=1),
        ),
    ]
