# Generated by Django 3.1.2 on 2020-11-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_auto_20201116_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='appointments',
        ),
        migrations.AddField(
            model_name='usuario',
            name='scheduled_appointments',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
