# Generated by Django 3.1.2 on 2020-11-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_auto_20201116_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameBarber',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('citas.barber',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='appointments',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
