# Generated by Django 3.1.2 on 2020-11-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_auto_20201116_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='appointments',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
