# Generated by Django 3.1.2 on 2020-11-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_auto_20201116_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsData',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('citas.appointment',),
        ),
    ]
