# Generated by Django 3.1.2 on 2020-11-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_auto_20201116_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='citas.namebarber'),
        ),
    ]
